# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U tox
  - pip install -U .
  - pip install -r requirements_dev.txt
  - pip install -U coveralls

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}
# script: make test

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
after_success:
  - coveralls
