# Development Dockerfile for jobcalc
#
# This file is used for development commands, and 
# interactive shell's with your package.
FROM mhoush/py-dev:latest

ENV PROJECT jobcalc
ENV PROJECT_PYTHON 3.5.0

RUN /bin/bash /entrypoint.sh install
